package loom.entity;

import loom.equilinox.ducktype.SoundReference;
import loom.equilinox.vanilla.VanillaSound;

public interface Tooltip {
    /**
     * @return the in-game name of the entity.
     */
    String name();

    /**
     * @return the description of the entity.
     */
    String description();

    /**
     * @return the price in the shop.
     */
    int price();

    /**
     * @return the points generated by each entity of this specie every game minute.
     */
    default int dpPerMin() {
        return 0;
    }

    /**
     * The range in which the entity roams by.
     * The vast majority of entities have either range 2 or 3,
     * except from small stones and shells, whose range is 1,
     * camels whose range is 4 and dolphins whose range is 5.
     * @return the roaming range
     */
    default int range() {
        return 2;
    }

    /**
     * Sound played by the entity when the entity is put down.
     * @return the sound played.
     */
    default SoundReference sound() {
        return VanillaSound.THUD;
    }
}
